version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DEFAULT_FLOWS_PATH=/app/flows
      - LANGFLOW_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./flows:/app/flows
    depends_on:
      - redis
